name: schedule deploy

on:
  schedule:
    - cron: '0 1 * * *'
    - cron: '0 5 * * *'
    - cron: '0 9 * * *'
    - cron: '0 13 * * *'
    - cron: '0 17 * * *'
    - cron: '0 21 * * *'

concurrency:
  group: run-bot
  cancel-in-progress: true

jobs:
  run-bot:
    uses: ./.github/workflows/workflow-run-bot.yml
    secrets:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      GUILD_ID: ${{ secrets.GUILD_ID }}
