name: run bot

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install nix action
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Nix develop
        run: nix develop

      - name: Install dependencies
        run: pnpm install

      - name: Run build
        run: pnpm build

      - name: Run bot
        run: pnpm start
