name: run bot

on:
  workflow_call:
    secrets:
      DISCORD_TOKEN:
        required: true
      GUILD_ID:
        required: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build project
        run: bun run build

      - name: Run Discord Bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
        run: |
          echo "🚀 Starting Discord Bot..."
          bun start
